config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#banner'
  resources :trips do
    resources :bookings, only: [:create]
    resources :saved_trips, only: [:create, :destroy]
    resources :activities, only: [:new, :create]
  end

  get '/home', to: "pages#home", as: :home
  get '/profile', to: "pages#profile"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :bookings, dependent: :destroy
  has_many :saved_trips, dependent: :destroy
  has_many :activities, dependent: :destroy


  mount_uploader :photo, PhotoUploader

  validates :name, presence: true
  validates :hotel_name, presence: true
  validates :location, presence: true
  validates :description, presence: true

   geocoded_by :location
  after_validation :geocode, if: :location_changed?

  def gmaps4rails_marker_picture
    {
      "rich_marker" =>  "<div class='my-marker'>It works!<img height='30' width='30' src='http://farm4.static.flickr.com/3212/3012579547_097e27ced9_m.jpg'/></div>"
    }
  end


end

app/models/user.rb
class User < ApplicationRecord
  # validates :username, presence: true
  has_many :trips, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :saved_trips, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  mount_uploader :photo, PhotoUploader

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook]

  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:create, :edit, :update, :destroy]
  def index
  end

  def show
    @booking = Booking.new
    @activities = @trip.activities
  end

  def new
    @categories = Category.all
    @trip = Trip.new
  end

  def create
    @trip = Trip.new(trip_params)
    @trip.user = @user
    if @trip.save
      redirect_to trip_path(@trip)
    else
      render :new
    end
  end

  def edit
    unless @trip.user == @user
      redirect_to trips_path
    end
  end

  def update
    if @trip.update(trip_params)
      redirect_to trip_path(@trip)
    else
      render :edit
    end
  end

  def destroy
    @trip.destroy
    redirect_to profile_path
  end

  private

  def trip_params
    params.require(:trip).permit(:name, :price_experience, :date, :description, :category_id, :hotel_name, :location, :photo, :photo_cache, :link_hotel)
  end

  def set_user
    @user = current_user
  end

  def set_trip
    @trip = Trip.find(params[:id])
  end

end

app/views/trips/_activity_card.html.erb
  <%= link_to activity.link_activity, target: :_blank do %>
    <div class="activity-card" style="background-image:linear-gradient(-225deg, rgba(1,1,1,0.2) 0%, rgba(1,1,1,0.2) 50%), url('<%= cl_image_path activity.photo %>');">
      <h4>
        <%= activity.name %>
      </h4>
      <span class="label-blue">
        <%= activity.activity_type %>
      </span>
      <p>
        <%= activity.description %>
      </p>
    </div>
 <% end %>

app/views/trips/_booking_form.html.erb
<div class="flight-name">
  <h3>
    Search flights
  </h3>
</div>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-offset-3 col-sm-6 col-md-offset-3 col-md-6">
      <div class="book-trip-form-wrapper text-center">
        <%= simple_form_for [trip, booking], input_html: { id: "trip-form" } do |f| %>
        <%= f.input :check_in, label: "Arrival", as: :date, html5: true  %>
        <%= f.input :check_out, label: "Departure", as: :date, html5: true  %>
        <%= f.input :guests, as: :integer, input_html: { class: "input-width-set", placeholder: "Input guest amount" } %>
        <%= f.input :current_location,  input_html: { class: "input-width-set", placeholder: "Flying from?" } %>
        <%= f.button :submit, "Search for flights!", class: "create_trip", id: "create_trip" %>
        <% end %>
        <%= render "shared/flashes" %>
      </div>
    </div>
  </div>
</div>


<!-- TODO: Change hotel to flight
  <!-- Link to the plane website -->
  <!--  save in database-->

app/views/trips/_carousel.html.erb
    <div id="carousel-example-generic" class="carousel slide carousel-fade" data-ride="carousel" data-interval="100000" style=" margin: 0px 100px ">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
          <% activities.each_with_index do |activity, index| %>
            <% if activity.photo? %>
              <li data-target="#carousel-example-generic" data-slide-to="<%= index + 1 %>"></li>
            <% end %>
          <% end %>
      </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner custom-carousel-height" role="listbox">
      <div class="item active trip-photo">
        <%= cl_image_tag trip.photo, class: "d-block w-100 carousel-show first-photo"%>
      <span class="label-brand bordered">
        $<%= @trip.price_experience %>
      </span>
      </div>
      <% activities.each do |activity| %>
        <% if activity.photo? %>
          <div class="item">
            <%= cl_image_tag activity.photo, class: "d-block w-100 carousel-show"%>
          </div>
        <% end %>
      <% end %>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

app/views/trips/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-offset-3 col-md-6">
      <%= simple_form_for(@trip) do |f| %>
      <%= f.input :name , label: "Give a name to your trip" %>
      <%= f.input :hotel_name %>
      <%= f.input :link_hotel, label: "Add a link to the hotel" %>
      <%= f.input :description %>
      <%= f.input :location %>
      <%= f.input :price_experience, label: "Price per night" %>
      <%= f.input :category_id, collection: @categories%>
      <%= f.input :photo %>
      <%= f.input :photo_cache, as: :hidden %>
      <%= f.submit class: "btn btn-pic text-center"%>
      <% end %>
    </div>
  </div>
</div>

app/views/trips/_hotel_information.html.erb
<div class="hotel-name">
  <h3>
    <%= link_to trip.hotel_name, trip.link_hotel, target: "_blank" %>
  </h3>
</div>
<div class="hotel-description">
  <div class="hotel-img">
    <%= image_tag 'hotel.svg' %>
  </div>
  <div class="hotel-details">
    <h5>
      <%= trip.hotel_name %>
    </h5>
    <p>
      <%= trip.description %>
    </p>
  </div>
    <% if current_user.trip_ids.include?(@trip.id) %>
    <div class="buttons-shared text-center">
      <%= link_to trip_path(@trip), method: :delete do %>
        <i class="fa fa-trash-o"></i>
      <% end %>
       <%= link_to edit_trip_path(@trip) do %>
        <i class="fa fa-pencil"></i>
      <% end %>
    </div>
    <% end %>
</div>



  <% if trip.activities.length > 0 %>
    <div class="container container-marged">
      <div class="activities-trip">
        <h3>Activities</h3>
      </div>
      <div class="row">
      <div class="col-xs-12">
      </div>
        <% activities.each do |activity| %>
        <div class="col-xs-12 col-sm-6 col-sm-offset-3">
          <%= render partial: "activity_card", locals: { activity: activity } %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>

app/views/trips/edit.html.erb
<div class="text-center edit-trip">
<h1>Edit Your trip</h1>
</div>

<div class="container">
  <div class="row">
  <%= render 'form' %>
  </div>
</div>

app/views/trips/new.html.erb
<div class="text-center edit-trip">
<h1>Share Your Trip</h1>
</div>
<%= render 'form' %>

app/views/trips/show.html.erb
<div class="booking-trip-page-wrapper">
  <div class="trip-name">
    <%= @trip.name %>
  </div>
  <div class="trip-location">
    <%= @trip.location %>
  </div>
  <% if @trip.activities.length > 0 %>
    <%= render partial: "carousel", locals: { trip: @trip, activities: @activities } %>
  <% else %>
    <div class="trip-card-banner" style="background-image: linear-gradient(rgba(255, 255, 255, 0) 90%,white 100%), url(<%= cl_image_path @trip.photo%>)">
      <span class="label-brand bordered">
        $<%= @trip.price_experience %>
      </span>
    </div>
  <% end %>

  <%= render partial: "hotel_information", locals: { trip: @trip, activities: @activities } %>


  <% if current_user.trip_ids.include?(@trip.id) %>
    <div class="text-center">
      <%= link_to "Add activity", new_trip_activity_path(@trip), class: "btn-pic " %>
    </div>
  <% else %>
    <%= render partial: "booking_form", locals: { trip: @trip, booking: @booking } %>
  <% end %>
</div>

<%= render partial: "shared/floating_button" %>