config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#banner'
  resources :trips do
    resources :bookings, only: [:create]
    resources :saved_trips, only: [:create, :destroy]
    resources :activities, only: [:new, :create]
  end

  get '/home', to: "pages#home", as: :home
  get '/profile', to: "pages#profile"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_card.html.erb
<div class="total-card">
  <div class="card-category">
    <% if user_bio %>
    <div class="bio">
      <% if trip.user.photo? %>
      <%= cl_image_tag trip.user.photo, class: "avatar" %>
      <% else %>
      <%= image_tag 'placeholder.png', class: "avatar" %>
      <% end %>
      <div class="bio-info">
        <span style="font-weight:bold">
          <%= trip.user.username %>
        </span>
        <span style="font-size: 12px">
          <%= trip.location %>
        </span>
      </div>
    </div>
    <% else %>
    <p>
      <%= trip.location %>
    </p>
    <% end %>
  </div>
  <% if trip.photo_url.nil? %>
    <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://picsum.photos/200/300/?random')";>
  <% else %>
    <div class="card" style="background-image: url(<%= cl_image_path trip.photo%>);">
      <%= image_tag trip.category.photo, class: 'category-image-card'%>
  <% end %>
  <% if booked %>
    <div class="card-description">
   <% if trip.bookings.count == 0%>
      <p>Not booked yet..</p>
    <% elsif trip.bookings.count == 1 %>
      <p><%= trip.bookings.count %> time booked</p>
      <% else %>
      <p> <%= trip.bookings.count  %> times booked</p>
    <% end %>
    </div>
  <% end %>



    <% if marker_booked %>
      <% user_trips = [] %>
      <% current_user.bookings.each do |booking| %>
        <% user_trips << booking.trip_id %>
      <% end %>
      <% if user_trips.include?(trip.id) %>
          <div class="card-description">
             <p>Booked!</p>
           </div>
      <% end %>
    <% end %>
      <% if edit_trip %>
      <div class="card-edit">
        <%= link_to trip_path(trip), class: "card-link" do %>
        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
        <% end %>
      </div>
      <% else %>
      <%= link_to trip_path(trip), class: "card-link" do %>
      <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
      <% end %>

      <% end %>
    </div>
    <% if add_save_trip && trip.user != current_user %>
    <div>

      <%= button_to "Save", trip_saved_trips_path(trip), class: "save_trip" %>
    </div>
    <% end %>
    <% if book_trip && trip.user != current_user  %>
      <div>
        <%= link_to "Book", trip_path(trip), class: "book_trip" %>
      </div>
    <% end %>
    <h4><%= trip.name %></h4>
    <p> <%= truncate trip.description, length: 100 %> </p>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="false">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_floating_button.html.erb
<div class="floating-button">
  <%= link_to new_trip_path do %>
  <i class="fa fa-plus"></i>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<div class="footer"></div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to home_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "new-logo-blue.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% avatar_url = current_user.photo.url || current_user.facebook_picture_url || "placeholder.png"%>
          <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
             <li>
              <%= link_to profile_path do %>
              <i class="fa fa-dashboard"></i> My page
              <% end %>
            </li>
            <li>
              <%= link_to edit_user_registration_path do %>
              <i class="fa fa-pencil"></i> Edit my profile
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
          <%= link_to "My page", profile_path %>
        </li>
        <li>
          <%= link_to "Edit my profile", edit_user_registration_path %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>

      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar_banner.html.erb
<div class="navbar-wagon-banner">
  <!-- Logo -->
  <%= link_to home_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "new_black_logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% avatar_url = current_user.photo.url || current_user.facebook_picture_url || "placeholder.png"%>
          <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
             <li>
              <%= link_to profile_path do %>
              <i class="fa fa-dashboard"></i> My page
              <% end %>
            </li>
            <li>
              <%= link_to edit_user_registration_path do %>
              <i class="fa fa-pencil"></i> Edit my profile
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
          <%= link_to "My page", profile_path %>
        </li>
        <li>
          <%= link_to "Edit my profile", edit_user_registration_path %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>

      </ul>
    </div>
  </div>
</div>